FROM rust:1.73-slim-bullseye

RUN apt --yes update && apt --yes install git pkg-config curl libssl-dev ca-certificates curl gnupg
RUN cargo install wasm-bindgen-cli sqlx-cli
RUN rustup target add wasm32-unknown-unknown

WORKDIR /usr/src/
COPY . .

ENTRYPOINT ["/bin/sh", "-c", "cd /usr/src/fullstack-rust-app/backend && sqlx migrate run; cargo run --bin backend -- --port 8000"]